name: Continuous Integration

# Triggers execute all tests workflow on pull request events
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - "api/**"
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          cd api
          npm install
          npm test
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_ID: ${{ secrets.AIRTABLE_ID }}
          AIRTABLE_PROJECTS_RESOURCES_CACHE_TABLE: ${{ secrets.AIRTABLE_PROJECTS_RESOURCES_CACHE_TABLE }}
          AIRTABLE_EVENTS_TABLE: ${{ secrets.AIRTABLE_EVENTS_TABLE }}
          AIRTABLE_EVENTS_SPEAKERS_TABLE: ${{ secrets.AIRTABLE_EVENTS_SPEAKERS_TABLE }}
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
          VIMEO_CLIENT_ID: ${{ secrets.VIMEO_CLIENT_ID }}
          VIMEO_CLIENT_SECRET: ${{ secrets.VIMEO_CLIENT_SECRET }}
          VIMEO_ACCESS_TOKEN: ${{ secrets.VIMEO_ACCESS_TOKEN }}
          SLACK_CHANNEL_VOLUNTEER_PROJECT_INTEREST: ${{ secrets.SLACK_CHANNEL_VOLUNTEER_PROJECT_INTEREST }}
          SLACK_SECRET_WEBHOOK_INITIAL_TRIAGE_TEST: ${{ secrets.SLACK_SECRET_WEBHOOK_INITIAL_TRIAGE_TEST }}
